### ISSUE TITLE
Automatically patch indicator-application in Juno.

### ISSUE THREAD

**Issue by eth-p** [eth-p/wingpanel-indicator-ayatana#6]
It appears that `indicator-application` needs its `.desktop` entry changed for this to work correctly. I'll need to find some way to patch that on install (or on run).

[More info.](https://www.linuxuprising.com/2018/08/how-to-re-enable-ayatana-appindicators.html)

**Comment by giovannicaligaris** [comment]
For ubuntu 18.04/Juno all you need to do is to add a # to OnlyShowIn

```
cat /etc/xdg/autostart/indicator-application.desktop 
[Desktop Entry]
Type=Application
Name=Indicator Application
Exec=/usr/lib/x86_64-linux-gnu/indicator-application/indicator-application-service
StartupNotify=false
Terminal=false
#OnlyShowIn=Unity;GNOME;
NoDisplay=false
AutostartCondition=GNOME3 unless-session gnome
```

That's it

**Comment by eth-p** [comment]
@giovannicaligaris  Thanks! That should be a pretty easy fix to add as a `.deb` post-install.

**Comment by eth-p** [comment]
This feature will be moved to [Indikeeper](https://github.com/indikeeper/indikeeper).
